- name: install dependencies
  apt: name=git
  
- name: clone cyanite repo
  git: repo=https://github.com/etsy/statsd.git dest=/opt/statsd

- name: configure statsd
  template: src=config.js dest=/opt/statsd/config.js
  notify: reload eye configs

- name: put statsd service descriptor
  template: src=statsd-eye.rb dest=/etc/eye/statsd.rb owner=root group=root mode=0644

- name: load config in eye
  command: bash -c "source /usr/local/rvm/scripts/rvm && eye l /etc/eye/apps.eye"

